# Generated by Django 3.2.13 on 2022-06-05 20:29

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringApp', '0002_website_is_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='time_interval',
            field=models.IntegerField(verbose_name=builtins.min),
        ),
        migrations.CreateModel(
            name='WebsitesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_begin_date', models.DateTimeField()),
                ('error_end_date', models.DateTimeField()),
                ('site_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='monitoringApp.website')),
            ],
        ),
    ]
