# Generated by Django 3.2.13 on 2022-06-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringApp', '0004_auto_20220605_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteshistory',
            name='site_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoringApp.website'),
        ),
    ]
