# Generated by Django 3.2.13 on 2022-06-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringApp', '0005_alter_websiteshistory_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteshistory',
            name='error_end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
