# Generated by Django 3.2.13 on 2022-06-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoringApp', '0006_alter_websiteshistory_error_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteshistory',
            name='error_end_date',
        ),
    ]
